import { loginAdmin, logoutAdmin, subscribeAuth, subscribeEvent, subscribeVotes, updateEvent, resetVotes, saveResult, subscribeHistory, deleteResult, subscribePresets, savePreset, deletePreset, subscribeSurveyResponses, resetSurveyResponses, isAdmin, isFirebaseConfigured } from './firebase-service.js';
const EVENT_ID=new URLSearchParams(location.search).get('event')||'main';
document.querySelector('#liveScreenLink').href=`/live?event=${encodeURIComponent(EVENT_ID)}`;
document.querySelector('#surveyScreenLink').href=`/survey-live?event=${encodeURIComponent(EVENT_ID)}`;
const base={question:'今夜、勝つのは誰だ？',nameA:'蒼井 レン',nameB:'赤城 カイ',nameC:'緑川 ソラ',optionCount:3,round:1,status:'open',showResults:true,timerMinutes:0,endsAt:null};
let state=base,votes={a:0,b:0,c:0},history=[],presets=[],stopEvent=null,stopVotes=null,stopHistory=null,stopPresets=null,stopSurvey=null,startingVote=false;const $=s=>document.querySelector(s);
function remainingSeconds(){const end=state.endsAt?.toMillis?.()??(state.endsAt?new Date(state.endsAt).getTime():0);return end?Math.max(0,Math.ceil((end-Date.now())/1000)):null}
function formatTime(seconds){return `${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`}
function renderTimer(){const remaining=remainingSeconds(),active=state.status==='open'&&remaining!==null,timer=$('#adminTimer');timer.hidden=!active;timer.classList.toggle('ending',active&&remaining<=30);$('#adminTimerValue').textContent=remaining===0?'締め切りました':formatTime(remaining||0);if(active&&remaining===0){$('#statusBadge').className='status-badge closed';$('#statusBadge').querySelector('b').textContent='時間切れ';document.querySelectorAll('[data-status]').forEach(x=>x.classList.remove('active'))}}
function render(){const isThree=Number(state.optionCount)!==2,t=votes.a+votes.b+(isThree?votes.c:0),a=t?Math.round(votes.a/t*100):(isThree?34:50),b=t?Math.round(votes.b/t*100):(isThree?33:50),c=isThree?100-a-b:0;document.body.classList.toggle('mode-two',!isThree);$('#adminQuestion').textContent=state.question;$('#adminNameA').textContent=state.nameA;$('#adminNameB').textContent=state.nameB;$('#adminNameC').textContent=state.nameC;$('#adminPercentA').textContent=a+'%';$('#adminPercentB').textContent=b+'%';$('#adminPercentC').textContent=c+'%';$('#adminCountA').textContent=votes.a.toLocaleString()+'票';$('#adminCountB').textContent=votes.b.toLocaleString()+'票';$('#adminCountC').textContent=votes.c.toLocaleString()+'票';$('#adminTotal').textContent=t.toLocaleString();$('#adminMeterA').style.width=a+'%';$('#adminMeterB').style.width=b+'%';$('#adminMeterC').style.width=c+'%';const labels={open:'受付中',paused:'一時停止中',closed:'終了'};$('#statusBadge').className='status-badge '+state.status;$('#statusBadge').querySelector('b').textContent=labels[state.status];document.querySelectorAll('[data-status]').forEach(x=>x.classList.toggle('active',x.dataset.status===state.status));$('#showResults').checked=state.showResults;const f=$('#adminForm');if(!f.contains(document.activeElement)){f.optionCount.value=isThree?'3':'2';f.timerMinutes.value=Number(state.timerMinutes)||0;f.question.value=state.question;f.nameA.value=state.nameA;f.nameB.value=state.nameB;f.nameC.value=state.nameC}$('#updatedAt').textContent=new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit',second:'2-digit'})+' 更新';renderTimer()}
function toast(m){const x=$('#toast');x.textContent=m;x.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.remove('show'),2200)}
async function patch(data,message){try{await updateEvent(EVENT_ID,data);toast(message)}catch(e){console.error(e);toast('更新に失敗しました')}}
function renderHistory(){const root=$('#historyList');root.innerHTML='';if(!history.length){root.innerHTML='<p class="empty-history">保存された結果はまだありません。</p>';return}history.forEach(item=>{const active=item.optionCount===2?['a','b']:['a','b','c'],max=Math.max(...active.map(k=>item.votes[k]||0)),names={a:item.nameA,b:item.nameB,c:item.nameC},date=item.savedAt?.toDate?.().toLocaleString('ja-JP')||'保存処理中';const row=document.createElement('article');row.className='history-item';row.innerHTML=`<div class="history-meta"><span>ROUND ${item.round}</span><time>${date}</time></div><h3></h3><div class="history-results"></div><div class="history-footer"><strong class="history-total">TOTAL ${(item.total||0).toLocaleString('ja-JP')} VOTES</strong><div class="history-actions"><a class="screen-result-link" target="_blank" rel="noopener">スクリーン表示 ↗</a><button class="delete-result" type="button">削除</button></div></div>`;row.querySelector('h3').textContent=item.question;row.querySelector('.screen-result-link').href=`/result?event=${encodeURIComponent(EVENT_ID)}&result=${encodeURIComponent(item.id)}`;row.querySelector('.delete-result').onclick=async()=>{if(!confirm(`ROUND ${item.round} の履歴を削除しますか？\nこの操作は元に戻せません。`))return;try{await deleteResult(EVENT_ID,item.id);toast(`ROUND ${item.round} の履歴を削除しました`)}catch(e){console.error(e);toast('履歴を削除できませんでした')}};const results=row.querySelector('.history-results');active.forEach(k=>{const line=document.createElement('div');if((item.votes[k]||0)===max&&item.total)line.classList.add('winner');line.innerHTML='<span></span><b></b>';line.querySelector('span').textContent=names[k];line.querySelector('b').textContent=`${(item.votes[k]||0).toLocaleString('ja-JP')}票`;results.appendChild(line)});root.appendChild(row)})}
function formSettings(){const d=new FormData($('#adminForm'));return{optionCount:Number(d.get('optionCount')),timerMinutes:Math.min(180,Math.max(0,Number(d.get('timerMinutes'))||0)),question:d.get('question').trim(),nameA:d.get('nameA').trim(),nameB:d.get('nameB').trim(),nameC:d.get('nameC').trim()}}
function applyPreset(item){const f=$('#adminForm');f.optionCount.value=String(item.optionCount||2);f.timerMinutes.value=Number(item.timerMinutes)||0;f.question.value=item.question||'';f.nameA.value=item.nameA||'';f.nameB.value=item.nameB||'';f.nameC.value=item.nameC||'';document.body.classList.toggle('mode-two',Number(item.optionCount)===2);toast(`「${item.name}」を選択しました`)}
function renderPresets(){const root=$('#presetList');root.innerHTML='';if(!presets.length){root.innerHTML='<span>保存済み設定はありません。</span>';return}presets.forEach(item=>{const row=document.createElement('div');row.className='preset-item';row.innerHTML='<button class="preset-select" type="button"><b></b><small></small></button><button class="preset-delete" type="button" aria-label="削除">削除</button>';row.querySelector('b').textContent=item.name;row.querySelector('small').textContent=`${item.optionCount||2}択・${Number(item.timerMinutes)||0}分｜${item.question||''}`;row.querySelector('.preset-select').onclick=()=>applyPreset(item);row.querySelector('.preset-delete').onclick=async()=>{if(!confirm(`「${item.name}」を削除しますか？`))return;try{await deletePreset(EVENT_ID,item.id);toast('保存設定を削除しました')}catch(e){console.error(e);toast('削除できませんでした')}};root.appendChild(row)})}
function startDashboard(){stopEvent?.();stopVotes?.();stopHistory?.();stopPresets?.();stopSurvey?.();stopEvent=subscribeEvent(EVENT_ID,d=>{state={...base,...d};render()});stopVotes=subscribeVotes(EVENT_ID,list=>{votes=list.reduce((x,v)=>{if(x[v.choice]!==undefined)x[v.choice]++;return x},{a:0,b:0,c:0});render()});stopHistory=subscribeHistory(EVENT_ID,list=>{history=list;renderHistory()});stopPresets=subscribePresets(EVENT_ID,list=>{presets=list;renderPresets()});stopSurvey=subscribeSurveyResponses(EVENT_ID,list=>{$('#surveyAnswerCount').textContent=`${list.length.toLocaleString('ja-JP')} ANSWERS`});$('#loginGate').hidden=true;$('#dashboard').hidden=false}
document.querySelectorAll('[data-status]').forEach(x=>x.onclick=async()=>{const status=x.dataset.status;if(status!=='open')return patch({status,endsAt:null},'ステータスを変更しました');if(startingVote)return;startingVote=true;const startButton=$('[data-status="open"]'),form=new FormData($('#adminForm')),minutes=Math.min(180,Math.max(0,Number(form.get('timerMinutes'))||0)),settings={optionCount:Number(form.get('optionCount')),question:form.get('question').trim(),nameA:form.get('nameA').trim(),nameB:form.get('nameB').trim(),nameC:form.get('nameC').trim()},hasVotes=Boolean(votes.a||votes.b||votes.c);startButton.disabled=true;try{let nextRound=Number(state.round)||1;if(hasVotes){await saveResult(EVENT_ID,state,votes);await resetVotes(EVENT_ID);nextRound+=1}await updateEvent(EVENT_ID,{...settings,round:nextRound,status:'open',surveyOpen:false,timerMinutes:minutes,endsAt:minutes?new Date(Date.now()+minutes*60000):null});toast(hasVotes?`設定を保存して ROUND ${nextRound} を開始しました`:minutes?`設定を保存し、${minutes}分の投票を開始しました`:'設定を保存して投票を開始しました')}catch(e){console.error(e);toast('次の投票を開始できませんでした')}finally{startingVote=false;startButton.disabled=false}});
$('#showResults').onchange=e=>patch({showResults:e.target.checked},'表示設定を変更しました');
$('#optionCount').onchange=e=>document.body.classList.toggle('mode-two',e.target.value==='2');
$('#adminForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);patch({optionCount:Number(d.get('optionCount')),timerMinutes:Math.min(180,Math.max(0,Number(d.get('timerMinutes'))||0)),question:d.get('question').trim(),nameA:d.get('nameA').trim(),nameB:d.get('nameB').trim(),nameC:d.get('nameC').trim()},'投票形式とイベント情報を保存しました')};
$('#savePreset').onclick=async()=>{const name=$('#presetName').value.trim();if(!name)return toast('設定名を入力してください');const settings=formSettings();if(!settings.question||!settings.nameA||!settings.nameB||(settings.optionCount===3&&!settings.nameC))return toast('質問と候補名を入力してください');try{await savePreset(EVENT_ID,name,settings);$('#presetName').value='';toast(`「${name}」を保存しました`)}catch(e){console.error(e);toast('設定を保存できませんでした')}};
$('#saveResult').onclick=async()=>{if(!votes.a&&!votes.b&&!votes.c)return toast('保存する投票結果がありません');try{await saveResult(EVENT_ID,state,votes);await updateEvent(EVENT_ID,{status:'closed'});toast(`ROUND ${state.round||1} の結果を保存しました`)}catch(e){console.error(e);toast('結果の保存に失敗しました')}};
$('#adminReset').onclick=async()=>{if(confirm('現在の結果を履歴へ保存して、すべての票をリセットしますか？'))try{if(votes.a||votes.b||votes.c)await saveResult(EVENT_ID,state,votes);await resetVotes(EVENT_ID);await updateEvent(EVENT_ID,{round:(Number(state.round)||1)+1,status:'paused'});toast('結果を保存して次のラウンドを準備しました')}catch(e){console.error(e);toast('リセットに失敗しました')}};
$('#openSurvey').onclick=()=>patch({surveyOpen:true,status:'paused',endsAt:null},'投票を停止してアンケート受付を開始しました');
$('#closeSurvey').onclick=()=>patch({surveyOpen:false},'アンケート受付を終了しました');
$('#resetSurvey').onclick=async()=>{if(!confirm('アンケート回答をすべて削除しますか？\nこの操作は元に戻せません。'))return;try{await updateEvent(EVENT_ID,{surveyOpen:false});await resetSurveyResponses(EVENT_ID);toast('アンケート回答をリセットしました')}catch(e){console.error(e);toast('回答をリセットできませんでした')}};
$('#loginForm').onsubmit=async e=>{e.preventDefault();const d=new FormData(e.target);$('#loginError').textContent='';try{const user=await loginAdmin(d.get('email'),d.get('password'));if(!await isAdmin(user.uid)){await logoutAdmin();throw new Error('not-admin')}startDashboard()}catch{$('#loginError').textContent='メールアドレス、パスワード、または管理者設定を確認してください'}};
$('#logoutButton').onclick=()=>logoutAdmin();
if(!isFirebaseConfigured()){$('#loginError').textContent='firebase-config.js にFirebase設定を入力してください'}
else subscribeAuth(async user=>{if(user&&!user.isAnonymous&&await isAdmin(user.uid))startDashboard();else{$('#loginGate').hidden=false;$('#dashboard').hidden=true}},false);
render();setInterval(renderTimer,1000);
